### ISSUE TITLE
Widget Form Scroll

### ISSUE THREAD

**Issue by SamDrummond** [WaimakaririGeospatial/LocateCoordinatesWidget#1]
When the user opens the widget the contents of the gui is too large for the default widget size and results in a horizontal scroll bar.

Please resolve by making the miminum width of the first table column in the locate panel 100px not 150px.

``` CSS
.jimu-widget-locatecoordinates .input-table > tbody > tr > .first {
    text-align: left;
    padding-right: 15px;
    min-width: 100px;
}
```
